export const ImageActionTypes = {
    UPLOAD_IMAGE_START: 'UPLOAD_IMAGE_START',
    UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
    UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',
    DELETE_IMAGE_START: 'DELETE_IMAGE_START',
    DELETE_IMAGE_SUCCESS: 'DELETE_IMAGE_SUCCESS',
    DELETE_IMAGE_FAILURE: 'DELETE_IMAGE_FAILURE',
};