export const INITIAL_IMAGES_DATA = [
	{
		account_id: 0,
		account_url: null,
		ad_type: 0,
		ad_url: "",
		animated: false,
		bandwidth: 0,
		datetime: 1606793218,
		deletehash: "b8aoUDO8eZbEmga",
		description: null,
		edited: "0",
		favorite: false,
		has_sound: false,
		height: 1228,
		id: "RAvKZrJ",
		in_gallery: false,
		in_most_viral: false,
		is_ad: false,
		link: "https://i.imgur.com/RAvKZrJ.jpg",
		name: "",
		nsfw: null,
		section: null,
		size: 701215,
		tags: [],
		title: null,
		type: "image/jpeg",
		views: 0,
		vote: null,
		width: 1818,
	},
	{
		account_id: 0,
		account_url: null,
		ad_type: 0,
		ad_url: "",
		animated: false,
		bandwidth: 0,
		datetime: 1606793190,
		deletehash: "lnaySVFUz0gOpuc",
		description: null,
		edited: "0",
		favorite: false,
		has_sound: false,
		height: 1228,
		id: "M60mTZd",
		in_gallery: false,
		in_most_viral: false,
		is_ad: false,
		link: "https://i.imgur.com/M60mTZd.jpg",
		name: "",
		nsfw: null,
		section: null,
		size: 656437,
		tags: [],
		title: null,
		type: "image/jpeg",
		views: 0,
		vote: null,
		width: 1818,
	}
];
